# Site settings
title: Cirriculum Vitae
name: Jonathon L Blank

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/jlblank5
 - title: LinkedIn
   url: https://www.linkedin.com/pub/rob-hinds/21/361/3b1

#Any buzzword skills you want to include
skills:
 - Mechanical Design
 - Experimental Design
 - Java
 - C++
 - Python
 - Solidworks
 - Autodesk Inventor and AutoCAD
 - MSC Adams
 - ANSYS
 - Abaqus

#Blogfeed is optional - including this will add JS to call the feed and populate blog list

#Work experience is required
roles:
 - title: Graduate Research Assistant
   start: August 2018
   end: Ongoing
   employer: University of Wisconsin-Madison Neuromuscular Biomechanics Research Lab
   description: Advisor - Dr. Darryl Thelen
 - title: Undergraduate Research Assistant
   start: February 2016
   end: May 2018
   employer: The Ohio State University Injury Biomechanics Research Center
   description: Advisors - Dr. John H. Bolte IV, Dr. Yun-Seok Kang
 - title: Engineering Intern
   start: May 2015
   end: August 2016
   employer: Kent State University Office of the University Architect
   description: Managed large-scale construction and renovation projects on the Kent State campus.
   
#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: May 2018
   subject: Mechanical Engineering
   school: The Ohio State University
 - level: Doctor of Philosophy (Ph.D.)
   date: Ongoing
   subject: Mechanical Engineering
   school: University of Wisconsin-Madison

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   I am a highly motivated student with a passion for applied research in musculoskeletal biomechanics.
